### PR TITLE
Upload videos to RP.

### PR DESCRIPTION
**Pull request by mgreensmith**
Send videos as well as screenshots to RP as test artifacts. Needed for https://github.com/wistia/wistia/pull/13309

Tested manually, see [this report](https://reportportal.wistia.cloud/ui/#wistia/launches/all/3317/687273/687274/log) for an example.

cc @wistia/quality-engineering

### CODE REVIEW

**Comment by samanthablasbalg** [comment]
Ahhhh this is so exciting!!! Is there a possibility that this is somehow cropping or affecting the aspect ratio of the videos? I can't see why it would, but the video in the RP link looks really widescreen, and the ones from the bento results are square:

RP:
Screen Shot 2021-04-27 at 11 44 29 AM

Github:
Screen Shot 2021-04-27 at 11 44 21 AM

**Review by qrush — APPROVED** [review]
Love reading video files into memory... if this works though :shipit:

**Comment by mgreensmith** [comment]
@samanthablasbalg Not sure about the aspect ratio thing, but I don't think that's gonna be related to this change, as the reporter plugin isn't doing any manipulation of the video; it's just uploading what it finds. I may have missed some config where we were setting aspect ratios or screen sizes elsewhere, and I'll double-check.

**Comment by mgreensmith** [comment]
Version bumped to 1.1.0 and published to https://www.npmjs.com/package/testcafe-reporter-reportportal-wistia

**Pull request merged**
